-- Week 11 seed: starter thematic networks

insert into public.networks (
  slug,
  name,
  description,
  tagline,
  emoji,
  primary_color,
  secondary_color,
  category,
  tags,
  points_multiplier,
  membership_type,
  coalition_enabled,
  welcome_bonus_points,
  is_featured,
  is_public,
  is_active,
  is_draft,
  multiplier_mode
)
values
  (
    'africa-loyalty',
    jsonb_build_object('fr', 'Africa Loyalty Network', 'en', 'Africa Loyalty Network', 'ar', 'شبكة الولاء الأفريقية', 'es', 'Red de Lealtad Africana', 'nl', 'Afrika Loyaliteitsnetwerk'),
    jsonb_build_object('fr', 'Réseau panafricain pour valoriser les commerces de la diaspora.', 'en', 'Pan-African network that rewards and connects diaspora businesses.', 'ar', 'شبكة أفريقية تكافئ وتربط أعمال الجاليات.', 'es', 'Red panafricana para recompensar y conectar negocios de la diáspora.', 'nl', 'Pan-Afrikaans netwerk dat diaspora-bedrijven beloont en verbindt.'),
    jsonb_build_object('fr', 'Consommez africain, gagnez plus.', 'en', 'Shop African, earn more.', 'ar', 'استهلك أفريقيًا واربح أكثر.', 'es', 'Consume africano, gana más.', 'nl', 'Koop Afrikaans, verdien meer.'),
    '🌍',
    '#F4A026',
    '#2D6A4F',
    'cultural',
    array['africa', 'diaspora', 'cultural']::text[],
    1.5,
    'validated',
    true,
    100,
    true,
    true,
    true,
    false,
    'additive'
  ),
  (
    'bio-local',
    jsonb_build_object('fr', 'Bio & Local', 'en', 'Bio & Local', 'ar', 'عضوي ومحلي', 'es', 'Bio y Local', 'nl', 'Bio & Lokaal'),
    jsonb_build_object('fr', 'Communauté de commerces responsables et de circuits courts.', 'en', 'Community of responsible businesses and local supply chains.', 'ar', 'مجتمع للتجارة المسؤولة وسلاسل التوريد المحلية.', 'es', 'Comunidad de comercios responsables y circuitos cortos.', 'nl', 'Community van verantwoorde bedrijven en korte ketens.'),
    jsonb_build_object('fr', 'Mieux consommer, localement.', 'en', 'Better choices, close to home.', 'ar', 'خيارات أفضل بالقرب منك.', 'es', 'Mejor consumo, más local.', 'nl', 'Betere keuzes, dicht bij huis.'),
    '🌿',
    '#52B788',
    null,
    'environmental',
    array['bio', 'local', 'sustainable', 'organic']::text[],
    1.3,
    'validated',
    false,
    0,
    false,
    true,
    true,
    false,
    'additive'
  ),
  (
    'halal-certified',
    jsonb_build_object('fr', 'Halal Certified', 'en', 'Halal Certified', 'ar', 'معتمد حلال', 'es', 'Certificado Halal', 'nl', 'Halal Gecertificeerd'),
    jsonb_build_object('fr', 'Réseau de commerces respectant les standards halal certifiés.', 'en', 'Network of businesses aligned with certified halal standards.', 'ar', 'شبكة أعمال ملتزمة بمعايير الحلال المعتمدة.', 'es', 'Red de comercios que cumplen estándares halal certificados.', 'nl', 'Netwerk van bedrijven die voldoen aan gecertificeerde halalnormen.'),
    jsonb_build_object('fr', 'Confiance certifiée, récompenses partagées.', 'en', 'Certified trust, shared rewards.', 'ar', 'ثقة معتمدة ومكافآت مشتركة.', 'es', 'Confianza certificada, recompensas compartidas.', 'nl', 'Gecertificeerd vertrouwen, gedeelde beloningen.'),
    '☪️',
    '#4EA8DE',
    null,
    'religious',
    array['halal', 'certified', 'islamic']::text[],
    1.2,
    'validated',
    true,
    0,
    false,
    true,
    true,
    false,
    'additive'
  ),
  (
    'women-owned',
    jsonb_build_object('fr', 'Women Owned Business', 'en', 'Women Owned Business', 'ar', 'أعمال مملوكة للنساء', 'es', 'Negocios Liderados por Mujeres', 'nl', 'Vrouwelijk Geleid Bedrijf'),
    jsonb_build_object('fr', 'Réseau qui valorise les commerces dirigés par des femmes.', 'en', 'Network highlighting women-led businesses and inclusive growth.', 'ar', 'شبكة تبرز الأعمال التي تقودها النساء والنمو الشامل.', 'es', 'Red que destaca negocios liderados por mujeres y crecimiento inclusivo.', 'nl', 'Netwerk dat vrouwelijk geleide bedrijven en inclusieve groei versterkt.'),
    jsonb_build_object('fr', 'Achetez engagé, soutenez l’égalité.', 'en', 'Shop with impact, support equality.', 'ar', 'تسوق بأثر وادعم المساواة.', 'es', 'Compra con impacto, apoya la igualdad.', 'nl', 'Koop met impact, steun gelijkheid.'),
    '💜',
    '#C77DFF',
    null,
    'social',
    array['women', 'equality', 'empowerment']::text[],
    1.25,
    'open',
    false,
    0,
    true,
    true,
    true,
    false,
    'additive'
  )
on conflict (slug)
do update set
  name = excluded.name,
  description = excluded.description,
  tagline = excluded.tagline,
  emoji = excluded.emoji,
  primary_color = excluded.primary_color,
  secondary_color = excluded.secondary_color,
  category = excluded.category,
  tags = excluded.tags,
  points_multiplier = excluded.points_multiplier,
  membership_type = excluded.membership_type,
  coalition_enabled = excluded.coalition_enabled,
  welcome_bonus_points = excluded.welcome_bonus_points,
  is_featured = excluded.is_featured,
  is_public = excluded.is_public,
  is_active = excluded.is_active,
  is_draft = excluded.is_draft,
  multiplier_mode = excluded.multiplier_mode,
  updated_at = now();
